version: "3.9"

services:
  dobro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: "npm start"
    
    # http://localhost:9080/bog/dobro/app/-/test.html
    # 
    # https://best-online-games.github.io/dobro/
